### ISSUE TITLE
Nav Panel Transparency Bug

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-app#162]
In v4, the nav panel no longer renders as transparent. 

![nov-15-2016 16-38-13](https://cloud.githubusercontent.com/assets/2886187/20325266/f3c62630-ab51-11e6-9da2-e3ed44f0785e.gif)

Tried referencing the text panel torkel mentioned and adding in the onRefresh and onRender stuff, but the Text Panel has markdown specific stuff.

![screenshot 2016-11-15 16 39 51](https://cloud.githubusercontent.com/assets/2886187/20325433/a45b7df6-ab52-11e6-9baa-007e108c27f1.png)

More importantly, the Nav Panel is specifically trying to override the transparency in the controller:
```
$scope.ctrl.panel.transparent = true;
```
https://github.com/raintank/worldping-app/blob/master/src/panels/nav-panel/module.js#L25

While also setting it in the dashboard:
```
"transparent": true,
```
https://github.com/raintank/worldping-app/blob/master/src/dashboards/rt-endpoint-summary.json#L28

Presumably, it should just be in the json for the dashboard, and not even be hanled in the controller, right?

Either way, tried to add these things but still having issues. Can we chat about it whenever you're back in action?

**Comment by torkelo** [comment]
ok, it can be fixed in the panel (panel needs to listen to refresh event and call render), but think this should be handled by Grafana so will fix it there (https://github.com/grafana/grafana/commit/f91a833e6a3d3c81dc68ab14999460ccb3902057) 

Just a personal opinion, the heavy use of transparent panels on the summery dashboard is in my view unnecessary. I think removing the transparency and the row titles makes it much more "readable"

With Transparency:
![image](https://cloud.githubusercontent.com/assets/10999/20340261/04bd05be-abe1-11e6-9a98-9422ca6ad338.png)


Without Transparency  (and row headings)
![image](https://cloud.githubusercontent.com/assets/10999/20340176/a1cb98b2-abe0-11e6-9310-fd87d5f6f9cf.png)

Think the panel backgrounds adds some structure that makes it easier to parse the dashboard and info.

**Comment by torkelo** [comment]
further attempts at trying to make the dashboard a little elegant by removing panel headings on the error panels and reducing panel headings on the graphs, make it more implicit that each column concerns DNS, PING, HTTP, and HTTPS etc. 

![image](https://cloud.githubusercontent.com/assets/10999/20340652/f1af0d26-abe2-11e6-91f3-53957da35905.png)

Of course this removes some affordances which could be valuable, but not a regular worldping user so I do not know. 

https://app.raintank.io/dashboard/db/worldping-endpoint-summary-torkel-edit?editorTab=Options&from=now-3h&to=now
