### ISSUE TITLE
fresh install -> datasource init failed because datasource raintank not found

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#58]
grafana3 beta3, fresh install, fresh worldping app install. (shows 1.0.1 in my plugin page in grafana)
after adding my first endpoint i got this:
![fototaart](https://cloud.githubusercontent.com/assets/20774/14295903/88972a2e-fb45-11e5-9f99-5bb68ca75b15.png)

**Comment by torkelo** [comment]
maybe this should be in the world-ping repo. maybe something with the worldping api key or the data is not there yet? I tried setting it up from scratch here on my mac added a new endpoint and after a while the ping dashboard started showing data

**Comment by torkelo** [comment]
lol, mistook this form the grafana repo, sorry :)

**Comment by Dieterbe** [comment]
note that i had previously removed the WP datasources, disabled the app and re-enabled the app. after that, the two WP datasources no longer seem to exist.

**Comment by torkelo** [comment]
Ok, so re-enabling did not create the datasource? Strange

**Comment by woodsaj** [comment]
Sounds like the problem was that the key entered was invalid.

The rest of the behaviour seems to be expected. Ie you deleted the datasources and then wondered why the datasources weren't there.  We store a flag in the jsonData to track if the datasource has been created already and we dont re-create it if that flag is set.  disabling/enabling the app wont clear that flag. But, on the config page you can clear that flag to re-create the datasources if needed.

So i think all that is needed here is to validate the apiKey when it is entered so users get immediate feedback if the key is invalid.

**Comment by Dieterbe** [comment]
big +1 re api key validation. i created #61 for that.

but automatically recreating the datasources if they are missing when the app is re-enabled sounds like a very useful and appropriate thing to do, why do we not do it? i saw some stuff related to this on the plugin config page but found it confusing.

**Comment by woodsaj** [comment]
Key validations has been added
