### ISSUE TITLE
I think sometimes the active org resets, or something

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-app#77]
when i login as my user, and then switch to raintank master account, and i load some endpoint dashboards that typically looks fine, but then sometimes they don't load anymore (had this with hortonworks). and if then go to endpoint list, i see the endpoint list for my original org, not RMA. even though that's still shown as active org in the menu. like below:
![org-mashup](https://cloud.githubusercontent.com/assets/20774/14658616/30f2e2e4-0663-11e6-9c9a-38cdc75acea4.png)

**Comment by Dieterbe** [comment]
the dash looked like this:
![fail](https://cloud.githubusercontent.com/assets/20774/14658797/90650c9c-0664-11e6-8dd3-d14f42684761.png)
i can also reproduce the dash not loading by switching the org in a different tab, but at least when i do that the active org also changes in the current tab.

with the issue in OP i think it was just time passing that triggered it.

**Comment by woodsaj** [comment]
The org a user is using is not a session variable, it is stored in the db and applies globally to all requests made by the user regardless of the browser or even comluter being used.  This is just how grafana works.

So you get the wrong data when loading a dashboard it is because the org has been switched from another tab/browser/computer.

**Comment by Dieterbe** [comment]
right. i tried to repro the original case (where i thought after a long time it resets the org) and couldn't repro it, so i must have switched it by accident.

would be nice if the grafana menu reflected the new org though.
