### ISSUE TITLE
500 Internal server error when adding new Endpoint

### ISSUE THREAD

**Issue by matejzero** [raintank/worldping-app#85]
Hello,

today I installed WorldPing to my Grafana server.

What I did:
- grafana-cli plugins install raintank-worldping-app
- systemctl restart grafana-server
- logged in to Grafana and went under Plugins->Apps->WorldPlugin
- entered API I created under Profile tab on grafana.net (created API with Admin privileges)
- clicked Update and everything went smoothly
- then I tried to add a new Endpoint and everything went sound:)

When adding an Endpoint, I get Unknown problem error and I see the following line in grafana log:
`Completed x.x.x.x admin "PUT /api/endpoints HTTP/1.1" 500 Internal Server Error 10 bytes in 233444us`

Matej

**Comment by woodsaj** [comment]
@matejzero The error logs from the system report 2 errors generated in the last 10minutes due to an endpoint trying to be created that has the same name as an existing endpoint.   So i suspect this might be the problem you are seeing. Endpoint names need to be unique within your Organisation.

We obviously need to improve the error response here so that is clear what the issue is.

**Comment by matejzero** [comment]
It works now... I didn't see the Endpoint. When I added a new Endpoint, the problematic one showed up as well.
